# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b22a14a34792d1439195c9f1da9ac0ac4930854839160e6fb944b20fb303c91f932c414d422b94878fd88e913d2fae87a0c73976745c1659c5ad38d5c57ec1f

test:
  secret_key_base: 1b2c1118ccf495638e2bfb77f332f9bf3cc33f946ebf5a71f87fb732740a6e89adbc1da357cc74485ba328603ba1530ad471eb557f2467884d49bdadbaae4d0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
